//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PraktikaodinEntities : DbContext
    {
        public PraktikaodinEntities()
            : base("name=PraktikaodinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Shoe> Shoe { get; set; }
        public virtual DbSet<ShoeFactory> ShoeFactory { get; set; }
        public virtual DbSet<Size> Size { get; set; }
        public virtual DbSet<ColorView> ColorView { get; set; }
        public virtual DbSet<ShoeInventory> ShoeInventory { get; set; }
        public virtual DbSet<ShoeView> ShoeView { get; set; }
        public virtual DbSet<SizeView> SizeView { get; set; }
    }
}
