//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoeFactory
    {
        public int ID_Product { get; set; }
        public int ShoeType_ID { get; set; }
        public int Size_ID { get; set; }
        public int Color_ID { get; set; }
        public double Price { get; set; }
    
        public virtual Color Color { private get; set; }
        public virtual Shoe Shoe { private get; set; }
        public virtual Size Size { private get; set; }
    }
}
