//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoeInventory
    {
        public string Обувь { get; set; }
        public int Размер { get; set; }
        public string Цвет { get; set; }
        public double Цена { get; set; }
    }
}
